version: '2'

services:
	applicationnavigator:
    build: applicationnavigator/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
  banneradmin:
    build: BannerAdmin/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
  communicationmanagement:
    build: CommunicationManagement/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
  employeessb:
    build: EmployeeSSB/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
      - BANSSUSER_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANSSUSER_PASSWORD:password
    volumes:
      - photos:/opt/xe/photos
  extensibility:
    build: Extensibility/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
      - BANSSUSER_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANSSUSER_PASSWORD:password
    volumes:
      - extensibility:/opt/xe/extensibility
  facultygradeentry:
    build: FacultyGradeEntry/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
      - BANSSUSER_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANSSUSER_PASSWORD:password
    volumes:
      - photos:/opt/xe/photos
  generalssb:
    build: GeneralSSB/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
      - BANSSUSER_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANSSUSER_PASSWORD:password
  studentadvisorssb:
    build: StudentAdvisorSSB/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
      - BANSSUSER_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANSSUSER_PASSWORD:password
    volumes:
      - photos:/opt/xe/photos
  studentapi:
    build: StudentApi/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
      - BANSSUSER_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANSSUSER_PASSWORD:password
  studentregistrationssb:
    build: StudentRegisrationSSB/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
      - BANSSUSER_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANSSUSER_PASSWORD:password
  studentssb:
    build: StudentSSB/.
    ports:
      - :8080
    environment:
      - TIMEZONE:America/Denver
      - BANPROXY_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANPROXY_PASSWORD:password
      - BANSSUSER_JDBC_URL:jdbc:oracle:thin:@//oracle.example.edu:1521/prod
      - BANSSUSER_PASSWORD:password
    volumes:
      - photos:/opt/xe/photos
volumes:
  - photos:
  - extensibility:
